apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: xyz-container
      image: xyz   
      
    - name: loggingsidecar-container
      image: loggingsidecar  